const {test,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path');
const {Readable,Writable}=require('stream');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'dailynote-admin-'));
process.env.DATA_DIR=path.join(root,'data');process.env.UPLOAD_DIR=path.join(root,'uploads');
delete process.env.REDIS_URL;delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.VERCEL;
const ds=require('../src/datastore'),handler=require('../src/server'),{makeUserRecord}=require('../src/auth');
after(()=>fs.rmSync(root,{recursive:true,force:true}));
async function request(method,url,body,token){
 const req=Readable.from(body?[JSON.stringify(body)]:[]);Object.assign(req,{method,url,headers:token?{authorization:'Bearer '+token}:{}});
 const chunks=[];const res=new Writable({write(c,e,cb){chunks.push(c);cb();}});res.writeHead=(status,headers)=>{res.status=status;res.headers=headers;res.headersSent=true;};
 const done=new Promise(resolve=>res.on('finish',resolve));await handler(req,res);await done;
 const buffer=Buffer.concat(chunks);let data;try{data=JSON.parse(buffer.toString());}catch{data=buffer;}return {status:res.status,data};
}
test('administration: rights, users, notification editing, shared appearance and private files',async()=>{
 await ds.insert('users',makeUserRecord('owner','test-admin-123'));
 const admin=(await request('POST','/api/auth/login',{username:'owner',password:'test-admin-123'})).data.token;
 assert.equal((await request('GET','/api/auth/me',null,admin)).data.role,'admin');
 const added=await request('POST','/api/admin/users',{username:'member',password:'test-member-123',active:true},admin);assert.equal(added.status,201);assert.equal(added.data.role,'member');assert.equal(added.data.password,undefined);
 const member=(await request('POST','/api/auth/login',{username:'member',password:'test-member-123'})).data.token;
 assert.equal((await request('GET','/api/admin/users',null,member)).status,403);
 assert.equal((await request('GET','/api/users',null,member)).status,403);
 assert.equal((await request('PUT','/api/admin/permissions/1',{role:'member',permissions:{}},admin)).status,400);
 assert.equal((await request('PUT','/api/admin/users/1',{username:'owner',active:false},admin)).status,400);
 assert.equal((await request('PUT','/api/admin/permissions/'+added.data.id,{permissions:{notifications:true}},admin)).status,200);
 assert.equal((await request('GET','/api/auth/me',null,member)).data.permissions.notifications,true);
 assert.equal((await request('PUT','/api/admin/permissions/'+added.data.id,{permissions:{notifications:true,users:true}},admin)).status,200);
 assert.equal((await request('PUT','/api/admin/users/1',{username:'owner',password:'overwritten-123'},member)).status,403);
 const note=await request('POST','/api/admin/notifications',{userId:added.data.id,message:'새 알림'},member);assert.equal(note.status,201);
 assert.equal((await request('PUT','/api/admin/notifications/'+note.data.id,{userId:added.data.id,message:'수정된 알림'},member)).status,200);
 assert.equal((await request('GET','/api/notifications',null,member)).data[0].message,'수정된 알림');
 assert.equal((await request('PUT','/api/admin/permissions/'+added.data.id,{role:'admin'},member)).status,403);
 assert.equal((await request('PUT','/api/admin/settings',{theme:'dark'},member)).status,403);
 assert.equal((await request('PUT','/api/admin/settings',{fontFamily:'serif',fontSize:18,spacing:'compact',theme:'white',background:'none'},admin)).status,200);
 const settings=(await request('GET','/api/settings')).data;assert.equal(settings.theme,'white');assert.equal(settings.fontSize,18);assert.equal(settings.fontFamily,'serif');
 assert.equal((await request('PUT','/api/admin/settings',{theme:'invalid'},admin)).status,400);
 const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2foAAAAASUVORK5CYII=';
 assert.equal((await request('PUT','/api/admin/settings',{background:'custom',imageData:png},admin)).status,200);
 const pub=await request('GET','/api/settings');assert.equal(pub.data.imageData,undefined);assert.ok(pub.data.backgroundUrl.startsWith('/api/background/1'));
 assert.equal((await request('GET','/api/background/1')).data.toString('base64'),png);
 assert.equal((await request('PUT','/api/admin/settings',{imageData:Buffer.from('<svg>bad</svg>').toString('base64')},admin)).status,400);
 const file=await request('POST','/api/upload',{filename:'member.txt',mime:'text/plain',data:Buffer.from('private').toString('base64')},member);
 assert.equal((await request('GET','/api/admin/files',null,member)).status,403);
 assert.equal((await request('GET','/api/admin/files/'+file.data.id,null,admin)).data.toString(),'private');
 assert.equal((await request('PUT','/api/admin/files/'+file.data.id,{originalName:'renamed.txt'},admin)).status,200);
 assert.equal((await request('GET','/api/files',null,member)).data[0].originalName,'renamed.txt');
 assert.equal((await request('DELETE','/api/admin/files/'+file.data.id,null,admin)).status,200);
 assert.equal((await request('DELETE','/api/admin/notifications/'+note.data.id,null,admin)).status,200);
 assert.equal((await request('PUT','/api/admin/users/'+added.data.id,{username:'member',active:false},admin)).status,200);
 assert.equal((await request('GET','/api/auth/me',null,member)).status,401);
 assert.equal((await request('POST','/api/auth/login',{username:'member',password:'test-member-123'})).status,401);
});
