const {test,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path');
const {Readable,Writable}=require('stream');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'dailynote-admin-'));
process.env.DATA_DIR=path.join(root,'data');process.env.UPLOAD_DIR=path.join(root,'uploads');
delete process.env.REDIS_URL;delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.VERCEL;
const ds=require('../src/datastore'),handler=require('../src/server'),{makeUserRecord}=require('../src/auth');
after(()=>fs.rmSync(root,{recursive:true,force:true}));
async function request(method,url,body,token){
 const req=Readable.from(body?[JSON.stringify(body)]:[]);Object.assign(req,{method,url,headers:token?{authorization:'Bearer '+token}:{}});
 const chunks=[];const res=new Writable({write(c,e,cb){chunks.push(c);cb();}});res.writeHead=(status,headers)=>{res.status=status;res.headers=headers;res.headersSent=true;};
 const done=new Promise(resolve=>res.on('finish',resolve));await handler(req,res);await done;
 const buffer=Buffer.concat(chunks);let data;try{data=JSON.parse(buffer.toString());}catch{data=buffer;}return {status:res.status,data};
}
test('administration: rights, users, notification editing, shared appearance and private files',async()=>{
 await ds.insert('users',makeUserRecord('owner','test-admin-123'));
 const admin=(await request('POST','/api/auth/login',{username:'owner',password:'test-admin-123'})).data.token;
 assert.equal((await request('GET','/api/auth/me',null,admin)).data.role,'admin');
 const added=await request('POST','/api/admin/users',{username:'member',password:'test-member-123',active:true},admin);assert.equal(added.status,201);assert.equal(added.data.role,'member');assert.equal(added.data.password,undefined);
 const member=(await request('POST','/api/auth/login',{username:'member',password:'test-member-123'})).data.token;
 assert.equal((await request('GET','/api/admin/users',null,member)).status,403);
 assert.equal((await request('GET','/api/users',null,member)).status,403);
 assert.equal((await request('PUT','/api/admin/permissions/1',{role:'member',permissions:{}},admin)).status,400);
 assert.equal((await request('PUT','/api/admin/users/1',{username:'owner',active:false},admin)).status,400);
 assert.equal((await request('PUT','/api/admin/permissions/'+added.data.id,{permissions:{notifications:true}},admin)).status,200);
 assert.equal((await request('GET','/api/auth/me',null,member)).data.permissions.notifications,true);
 assert.equal((await request('PUT','/api/admin/permissions/'+added.data.id,{permissions:{notifications:true,users:true}},admin)).status,200);
 assert.equal((await request('PUT','/api/admin/users/1',{username:'owner',password:'overwritten-123'},member)).status,403);
 const note=await request('POST','/api/admin/notifications',{userId:added.data.id,message:'새 알림'},member);assert.equal(note.status,201);
 assert.equal((await request('PUT','/api/admin/notifications/'+note.data.id,{userId:added.data.id,message:'수정된 알림'},member)).status,200);
 assert.equal((await request('GET','/api/notifications',null,member)).data[0].message,'수정된 알림');
 assert.equal((await request('PUT','/api/admin/permissions/'+added.data.id,{role:'admin'},member)).status,403);
 assert.equal((await request('PUT','/api/admin/settings',{theme:'dark'},member)).status,403);
 assert.equal((await request('PUT','/api/admin/settings',{fontFamily:'serif',fontSize:18,spacing:'compact',theme:'white',background:'none'},admin)).status,200);
 const settings=(await request('GET','/api/settings')).data;assert.equal(settings.theme,'white');assert.equal(settings.fontSize,18);assert.equal(settings.fontFamily,'serif');
 assert.equal((await request('PUT','/api/admin/settings',{theme:'invalid'},admin)).status,400);
 const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2foAAAAASUVORK5CYII=';
 assert.equal((await request('PUT','/api/admin/settings',{background:'custom',imageData:png},admin)).status,200);
 const pub=await request('GET','/api/settings');assert.equal(pub.data.imageData,undefined);assert.ok(pub.data.backgroundUrl.startsWith('/api/background/1'));
 assert.equal((await request('GET','/api/background/1')).data.toString('base64'),png);
 assert.equal((await request('PUT','/api/admin/settings',{imageData:Buffer.from('<svg>bad</svg>').toString('base64')},admin)).status,400);
 const file=await request('POST','/api/upload',{filename:'member.txt',mime:'text/plain',data:Buffer.from('private').toString('base64')},member);
 assert.equal((await request('GET','/api/admin/files',null,member)).status,403);
 assert.equal((await request('GET','/api/admin/files/'+file.data.id,null,admin)).data.toString(),'private');
 assert.equal((await request('PUT','/api/admin/files/'+file.data.id,{originalName:'renamed.txt'},admin)).status,200);
 assert.equal((await request('GET','/api/files',null,member)).data[0].originalName,'renamed.txt');
 assert.equal((await request('DELETE','/api/admin/files/'+file.data.id,null,admin)).status,200);
 assert.equal((await request('DELETE','/api/admin/notifications/'+note.data.id,null,admin)).status,200);
 assert.equal((await request('PUT','/api/admin/users/'+added.data.id,{username:'member',active:false},admin)).status,200);
 assert.equal((await request('GET','/api/auth/me',null,member)).status,401);
 assert.equal((await request('POST','/api/auth/login',{username:'member',password:'test-member-123'})).status,403);
});
test('notice pagination limits payload and searches all records with permission checks',async()=>{
 const owner=await ds.insert('users',{...makeUserRecord('paged-owner','test-paged-123'),role:'admin'});
 const token=(await request('POST','/api/auth/login',{username:'paged-owner',password:'test-paged-123'})).data.token;
 for(let i=0;i<75;i++)await ds.insert('notifications',{userId:owner.id,title:'pagination '+i,message:'page-body',isRead:i%2===0,createdAt:'2090-01-01T00:00:00Z'});
 const base='/api/admin/notifications?limit=30&recipient='+owner.id+'&query=pagination';
 const first=(await request('GET',base,null,token)).data;
 assert.equal(first.items.length,30);assert.equal(first.filteredTotal,75);assert.equal(first.nextOffset,30);
 const second=(await request('GET',base+'&offset=30',null,token)).data;
 const last=(await request('GET',base+'&offset=60',null,token)).data;
 assert.equal(second.items.length,30);assert.equal(last.items.length,15);assert.equal(last.nextOffset,null);
 assert.equal(new Set([...first.items,...second.items,...last.items].map(n=>n.id)).size,75);
 const search=(await request('GET',base.replace('query=pagination','query=pagination%200')+'&read=read',null,token)).data;
 assert.equal(search.items.length,1);assert.equal(search.items[0].title,'pagination 0');
 assert.equal((await request('GET',base)).status,401);
 const member=await ds.insert('users',{...makeUserRecord('page-member','test-paged-123'),role:'member',permissions:{}});
 const memberToken=(await request('POST','/api/auth/login',{username:member.username,password:'test-paged-123'})).data.token;
 assert.equal((await request('GET',base,null,memberToken)).status,403);
 // Release this scenario's two seats before subsequent independent admin scenarios.
 await ds.update('users',owner.id,{active:false});
 await ds.update('users',member.id,{active:false});
});
test('registration waits for approval, rejects privileged fields and supports rejection',async()=>{
 const admin=(await request('POST','/api/auth/login',{username:'owner',password:'test-admin-123'})).data.token;
 const registration={username:'new-user',password:'new-password-123',passwordConfirmation:'new-password-123',role:'admin',active:true,permissions:{users:true}};
 assert.equal((await request('POST','/api/auth/register',{...registration,passwordConfirmation:'different'})).status,400);
 const result=await request('POST','/api/index?path=auth/register',registration);
 assert.equal(result.status,201);assert.equal(result.data.token,undefined);
 assert.equal((await request('POST','/api/auth/register',registration)).status,409);
 const stored=await ds.findOne('users',u=>u.username===registration.username);
 assert.notEqual(stored.password,registration.password);assert.equal(stored.role,'member');assert.equal(stored.active,false);assert.deepEqual(stored.permissions,{});
 const pending=await request('POST','/api/auth/login',registration);assert.equal(pending.status,403);assert.match(pending.data.message,/승인/);
 assert.equal((await request('POST','/api/auth/login',{...registration,password:'wrong'})).status,401);
 const listed=(await request('GET','/api/admin/users',null,admin)).data.find(u=>u.id===stored.id);assert.equal(listed.approval,'pending');assert.equal(listed.password,undefined);
 assert.equal((await request('POST','/api/admin/users/'+stored.id+'/approve',{})).status,401);
 assert.equal((await request('POST','/api/admin/users/'+stored.id+'/approve',{},admin)).data.approval,'approved');
 assert.equal((await request('POST','/api/admin/users/'+stored.id+'/approve',{},admin)).status,400);
 const login=await request('POST','/api/auth/login',registration);assert.equal(login.status,200);assert.ok(login.data.token);
 const me=(await request('GET','/api/auth/me',null,login.data.token)).data;assert.equal(me.role,'member');assert.ok(require('../src/permissions').adminKeys.every(key=>me.permissions[key]===false));assert.ok(require('../src/permissions').basicKeys.every(key=>me.permissions[key]===true));
 const rejected={username:'rejected-user',password:'reject-password-123',passwordConfirmation:'reject-password-123'};
 assert.equal((await request('POST','/api/auth/register',rejected)).status,201);
 const rejectedUser=await ds.findOne('users',u=>u.username===rejected.username);
 assert.equal((await request('POST','/api/admin/users/'+rejectedUser.id+'/approve',{},login.data.token)).status,403);
 assert.equal((await request('POST','/api/admin/users/'+rejectedUser.id+'/reject',{},admin)).data.approval,'rejected');
 const denied=await request('POST','/api/auth/login',rejected);assert.equal(denied.status,403);assert.match(denied.data.message,/반려/);
});
test('administrator password reset validates input and revokes existing sessions',async()=>{
 const admin=(await request('POST','/api/auth/login',{username:'owner',password:'test-admin-123'})).data.token;
 const user=await ds.findOne('users',u=>u.username==='new-user');
 const oldSession=(await request('POST','/api/auth/login',{username:'new-user',password:'new-password-123'})).data.token;
 const url='/api/admin/users/'+user.id+'/reset-password';
 const body={password:'reset-password-456',passwordConfirmation:'reset-password-456'};
 assert.equal((await request('POST',url,body,oldSession)).status,403);
 const delegated=(await request('POST','/api/admin/users',{username:'delegated',password:'delegated-password'},admin)).data;
 await request('PUT','/api/admin/permissions/'+delegated.id,{permissions:{users:true}},admin);
 const manager=(await request('POST','/api/auth/login',{username:'delegated',password:'delegated-password'})).data.token;
 assert.equal((await request('POST',url,body,manager)).status,403);
 assert.equal((await request('POST',url,{password:'short',passwordConfirmation:'short'},admin)).status,400);
 assert.equal((await request('POST',url,{...body,passwordConfirmation:'wrong'},admin)).status,400);
 assert.equal((await request('GET','/api/auth/me',null,oldSession)).status,200);
 assert.equal((await request('POST',url,body,admin)).status,200);
 assert.equal((await request('GET','/api/auth/me',null,oldSession)).status,401);
 assert.equal((await request('POST','/api/auth/login',{username:'new-user',password:'new-password-123'})).status,401);
 const login=await request('POST','/api/auth/login',{username:'new-user',password:body.password});assert.equal(login.status,200);
 assert.equal((await request('GET','/api/auth/me',null,login.data.token)).data.mustChangePassword,true);
 for(const path of ['/api/worklogs','/api/notifications','/api/files','/api/admin/users']) {const blocked=await request('GET',path,null,login.data.token);assert.equal(blocked.status,403);assert.equal(blocked.data.code,'PASSWORD_CHANGE_REQUIRED');}
 const change={currentPassword:body.password,password:'my-personal-password',passwordConfirmation:'my-personal-password'};
 assert.equal((await request('POST','/api/auth/change-password',{...change,currentPassword:'wrong'},login.data.token)).status,400);
 assert.equal((await request('POST','/api/auth/change-password',{...change,passwordConfirmation:'mismatch'},login.data.token)).status,400);
 assert.equal((await request('POST','/api/auth/change-password',{...change,password:body.password,passwordConfirmation:body.password},login.data.token)).status,400);
 assert.equal((await request('PUT','/api/users/'+user.id,{password:'bypass-password'},login.data.token)).status,403);
 const changed=await request('POST','/api/index?path=auth/change-password',change,login.data.token);assert.equal(changed.status,200);assert.equal(changed.data.mustChangePassword,false);assert.notEqual(changed.data.token,login.data.token);
 assert.equal((await request('GET','/api/auth/me',null,login.data.token)).status,401);
 assert.equal((await request('GET','/api/worklogs',null,changed.data.token)).status,200);
 assert.equal((await request('POST','/api/auth/login',{username:'new-user',password:body.password})).status,401);
 const personalLogin=await request('POST','/api/auth/login',{username:'new-user',password:change.password});assert.equal(personalLogin.status,200);assert.equal(personalLogin.data.mustChangePassword,false);
 const stored=await ds.findOne('users',u=>u.id===user.id);assert.notEqual(stored.password,body.password);assert.equal(stored.role,'member');assert.equal(stored.active,true);
});

test('basic user permissions enforce journal, personal file and notification actions immediately',async()=>{
 const admin=(await request('POST','/api/auth/login',{username:'owner',password:'test-admin-123'})).data.token;
 const added=(await request('POST','/api/admin/users',{username:'basic-rights',password:'basic-rights-123'},admin)).data;
 const member=(await request('POST','/api/auth/login',{username:'basic-rights',password:'basic-rights-123'})).data.token;
 const {basicKeys}=require('../src/permissions');
 assert.ok(basicKeys.every(key=>added.permissions[key]===true));
 const log=await request('POST','/api/worklogs',{workDate:'2026-10-01',todo:[{task:'원본',checked:false,children:[]}]},member);assert.equal(log.status,201);
 const file=await request('POST','/api/upload',{filename:'basic.txt',mime:'text/plain',data:Buffer.from('basic').toString('base64')},member);assert.equal(file.status,201);
 await request('PUT','/api/admin/permissions/'+added.id,{permissions:Object.fromEntries(basicKeys.map(key=>[key,false]))},admin);
 const denied=[['GET','/api/worklogs'],['POST','/api/worklogs'],['PUT','/api/worklogs/'+log.data.id],['DELETE','/api/worklogs/'+log.data.id],['GET','/api/files'],['POST','/api/upload'],['GET','/api/upload/'+file.data.id],['GET','/api/files/'+file.data.id],['DELETE','/api/files/'+file.data.id],['GET','/api/notifications'],['PUT','/api/notifications/1']];
 for(const [method,path] of denied){const response=await request(method,path,method==='POST'||method==='PUT'?{}:null,member);assert.equal(response.status,403,path);assert.equal(response.data.code,'PERMISSION_DENIED');}
 assert.equal((await ds.findOne('work_logs',w=>w.id===log.data.id)).todo[0].task,'원본');
 await request('PUT','/api/admin/permissions/'+added.id,{permissions:{worklogRead:true}},admin);
 assert.equal((await request('GET','/api/worklogs',null,member)).status,200);
 assert.equal((await request('PUT','/api/worklogs/'+log.data.id,{todo:[]},member)).status,403);
 assert.equal((await request('GET','/api/files',null,member)).status,403);
 await request('PUT','/api/admin/permissions/'+added.id,{permissions:{worklogEdit:true,fileDownload:true}},admin);
 const edit=await request('PUT','/api/worklogs/'+log.data.id,{todo:[{task:'바로 수정',checked:false,children:[]}]},member);assert.equal(edit.status,200);
 assert.equal((await request('GET','/api/upload/'+file.data.id,null,member)).data.toString(),'basic');
 assert.equal((await request('DELETE','/api/upload/'+file.data.id,null,member)).status,403);
 assert.equal((await request('GET','/api/admin/users',null,member)).status,403);
});


test('shared notices: one post, per-user reads, all-user edits, new users and denied rights',async()=>{
 const admin=(await request('POST','/api/auth/login',{username:'owner',password:'test-admin-123'})).data.token;
 const added=(await request('POST','/api/admin/users',{username:'notice-reader',password:'notice-reader-123'},admin)).data;
 const member=(await request('POST','/api/auth/login',{username:'notice-reader',password:'notice-reader-123'})).data.token;
 assert.equal((await request('POST','/api/admin/notifications',{message:'권한 없음'},member)).status,403);
 assert.equal((await request('POST','/api/admin/notifications',{message:'   '},admin)).status,400);
 assert.equal((await request('POST','/api/admin/notifications',{title:'x'.repeat(121),message:'내용'},admin)).status,400);
 const post=await request('POST','/api/admin/notifications',{title:'전사 공지',message:'공지 게시 테스트'},admin);assert.equal(post.status,201);assert.equal(post.data.count,1);const id=post.data.id;
 assert.equal((await ds.findAll('notifications')).filter(n=>n.id===id).length,1);
 assert.equal((await request('GET','/api/notifications/'+id,null,member)).data.title,'전사 공지');
 await request('PUT','/api/notifications/'+id,{},member);
 assert.equal((await request('GET','/api/notifications/'+id,null,member)).data.isRead,true);
 assert.equal((await request('GET','/api/notifications/'+id,null,admin)).data.isRead,false);
 let summary=(await request('GET','/api/admin/notifications',null,admin)).data.find(n=>n.id===id);assert.equal(summary.readCount,1);
 assert.equal((await request('PUT','/api/admin/notifications/'+id,{title:'수정 제목',message:'수정 내용'},admin)).status,200);
 for(const token of [admin,member]){const n=(await request('GET','/api/notifications/'+id,null,token)).data;assert.equal(n.message,'수정 내용');assert.equal(n.isRead,false);}
 const newUser=(await request('POST','/api/admin/users',{username:'later-reader',password:'later-reader-123'},admin)).data;
 const later=(await request('POST','/api/auth/login',{username:'later-reader',password:'later-reader-123'})).data.token;
 assert.equal((await request('GET','/api/notifications/'+id,null,later)).data.title,'수정 제목');
 assert.equal((await request('DELETE','/api/admin/notifications/'+id,null,member)).status,403);
 assert.equal((await request('DELETE','/api/admin/notifications/'+id,null,admin)).status,200);
 for(const token of [admin,member,later])assert.equal((await request('GET','/api/notifications/'+id,null,token)).status,404);
});
