const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('public/boards.js','utf8');
function setup(permissions={},owner=2){
 const nodes=new Map();class Node{constructor(tag,text='',cls=''){this.tag=tag;this.textContent=text;this.className=cls;this.children=[];this.attrs={};this.dataset={};}append(...children){this.children.push(...children);}replaceChildren(...children){this.children=children;}setAttribute(k,v){this.attrs[k]=v;}querySelectorAll(tag){return this.children.filter(n=>n.tag===tag);}}
 const context={URL,Date,AppIcons:{render(){}},make:(...args)=>new Node(...args),$:id=>{if(!nodes.has(id))nodes.set(id,new Node('div'));return nodes.get(id);},user:{userId:1},board:{id:4,name:'개발'},post:null,generation:1,loading:false,cursor:null,rows:[{id:9,boardId:4,userId:owner,title:'글',preview:'본문',author:'사용자',createdAt:'2026-10-01',tags:[]}],can:key=>permissions[key]===true,manager:()=>false,listCache:new Map(),location:{href:'https://example.test/#boards/4'},navigator:{clipboard:{writeText:async url=>context.copied=url}},UIShell:{dropdown:{close(){context.closed=true;},open(menu,opener){menu.open=true;context.opened=opener;}}},action(label,fn,menu){const node=new Node('button',label);node.onclick=fn;menu.append(node);return node;},api:async()=>{context.calls=(context.calls||0)+1;return {title:'전체 글',attachments:[]};},openEditor:value=>context.edited=value,loadPage:async()=>context.loaded=true};
 vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function renderList()'),source.indexOf("$('board-load-more').addEventListener"))+source.slice(source.indexOf('async function share('),source.indexOf("for(const b of dialogs.querySelectorAll('[data-board-close]'))")),context);
 return {c:context,nodes,buttons:()=>nodes.get('board-menu-items').children};
}
test('every row has a separate link and more button; other authors can share only',()=>{const x=setup({boardEdit:true,boardDelete:true});x.c.renderList();const row=x.nodes.get('board-content').children[0];assert.deepEqual(row.children.map(n=>n.tag),['a','button']);assert.equal(row.children[0].href,'#boards/4/posts/9');row.children[1].onclick();assert.deepEqual(x.buttons().map(n=>n.textContent),['공유 / 링크 복사']);assert.equal(row.children[1].attrs['aria-controls'],'board-menu');});
test('owners see only granted edit and delete actions',()=>{for(const permission of ['boardEdit','boardDelete']){const x=setup({[permission]:true},1);x.c.openPostMenu(x.c.rows[0],{});assert.deepEqual(x.buttons().map(n=>n.textContent),permission==='boardEdit'?['수정','공유 / 링크 복사']:['공유 / 링크 복사','삭제']);}});
test('sharing from the list copies the selected post URL',async()=>{const x=setup();await x.c.share(x.c.rows[0]);assert.equal(x.c.copied,'https://example.test/#boards/4/posts/9');});
test('delete requires confirmation, keeps rows on failure, and refreshes on success',async()=>{const x=setup({boardDelete:true},1);x.c.openPostMenu(x.c.rows[0],{});const button=x.buttons().at(-1);await button.onclick();assert.equal(x.c.calls,undefined);x.c.api=async()=>{throw Error('실패');};await assert.rejects(button.onclick(),/실패/);assert.equal(x.c.rows.length,1);x.c.api=async()=>({});await button.onclick();assert.equal(x.c.rows.length,0);assert.equal(x.c.loaded,true);});
test('late edit response after leaving the page cannot open an editor',async()=>{const x=setup({boardEdit:true},1);let finish;x.c.api=()=>new Promise(resolve=>finish=resolve);x.c.openPostMenu(x.c.rows[0],{});const pending=x.buttons()[0].onclick();x.c.generation++;finish({title:'이전 화면'});await pending;assert.equal(x.c.edited,undefined);});
