const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(width=390,height=844){
 const handlers={},document={activeElement:null,addEventListener(k,f){handlers[k]=f}},window={handlers:{},addEventListener(k,f){this.handlers[k]=f}};
 class Node{constructor(rect){this.rect=rect;this.attrs={};this.handlers={};this.style={};this.dataset={};this.hidden=false;this.isConnected=true;this.children=[];this.classList={add(){}};}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.handlers[k]=f;}querySelectorAll(){return this.children;}getBoundingClientRect(){return this.rect;}getClientRects(){return [this.rect];}contains(n){return n===this||this.children.includes(n);}matches(s){return s==='button,a';}focus(){document.activeElement=this;}}
 class Dialog extends Node{show(){this.open=true;}showModal(){throw Error('Action menu must never be modal');}close(){this.open=false;}}
 vm.runInNewContext(fs.readFileSync('public/ui-shell.js','utf8'),{window,document,HTMLDialogElement:Dialog,innerWidth:width,innerHeight:height});
 const opener=new Node({right:380,bottom:800,top:758}),menu=new Dialog({width:280,height:200});menu.id='menu';menu.children=[new Node({}),new Node({})];return {dropdown:window.UIShell.dropdown,opener,menu,handlers,document,window,Node};
}
test('dropdown anchors above near bottom, uses nonmodal show, toggles and restores focus',()=>{const x=setup();x.dropdown.open(x.menu,x.opener);assert.equal(x.menu.open,true);assert.equal(x.menu.style.left,'98px');assert.equal(x.menu.style.top,'552px');assert.equal(x.opener.attrs['aria-haspopup'],'menu');x.dropdown.open(x.menu,x.opener);assert.equal(x.menu.open,false);assert.equal(x.document.activeElement,x.opener);});
test('dropdown closes on outside click, Escape, Tab and route changes; keyboard stays in menu',()=>{const x=setup(),event=key=>({key,target:x.menu.children[0],preventDefault(){},stopImmediatePropagation(){}});x.dropdown.open(x.menu,x.opener);x.handlers.keydown(event('ArrowDown'));assert.equal(x.document.activeElement,x.menu.children[1]);x.handlers.keydown(event('Escape'));assert.equal(x.document.activeElement,x.opener);x.dropdown.open(x.menu,x.opener);x.handlers.pointerdown({target:new x.Node({})});assert.equal(x.menu.open,false);x.dropdown.open(x.menu,x.opener);x.handlers.keydown(event('Tab'));assert.equal(x.menu.open,false);x.dropdown.open(x.menu,x.opener);x.window.handlers.hashchange();assert.equal(x.menu.open,false);});
test('all production ellipsis adapters and harness use common dropdown',()=>{for(const file of ['boards.js','board-admin.js','journal-controls.js','calendar.js','memo.js','design-harness.js'])assert.match(fs.readFileSync('public/'+file,'utf8'),/UIShell\.dropdown\.open/);const s=fs.readFileSync('public/boards.js','utf8');assert.match(s,/board-post-more/);assert.match(s,/p\.userId===user\.userId\|\|manager\(\)/);assert.ok(!s.includes("$('board-menu').showModal()"));});
