const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');const fs=require('fs'),http=require('http'),os=require('os'),path=require('path'),assert=require('assert/strict');
const app=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'memo-browser-'));process.env.DATA_DIR=tmp;delete process.env.VERCEL;delete process.env.REDIS_URL;delete process.env.UPSTASH_REDIS_REST_URL;
const ds=require(app+'/src/datastore'),{makeUserRecord}=require(app+'/src/auth');let server,browser;
(async()=>{await ds.insert('users',{...makeUserRecord('메모검토','local-test-password'),role:'admin',approval:'approved'});server=http.createServer(require(app+'/src/server'));await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;browser=await chromium.launch({...(process.env.BROWSER_EXECUTABLE_PATH?{executablePath:process.env.BROWSER_EXECUTABLE_PATH}:{}),headless:true,args:['--no-sandbox','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+port);await page.locator('#username').fill('메모검토');await page.locator('#password').fill('local-test-password');await page.locator('.login-btn').click();await page.locator('#main-section').waitFor({state:'visible'});await page.waitForFunction(()=>document.getElementById('loading-overlay').hidden);await page.locator('#sidebar-open').click();await page.locator('[data-view=memos]').click();await page.locator('#open-memo-btn').click();await page.locator('#memo-title').fill('회의 메모');await page.locator('#memo-body').fill('오늘의 회의 내용을 정리합니다.\n화면 디자인과 다음 일정을 확인합니다.');await page.locator('#memo-format-toggle').click();await page.locator('#memo-font').selectOption('serif');await page.locator('#memo-undo').click();assert.equal(await page.locator('#memo-font').inputValue(),'sans-serif');await page.locator('#memo-redo').click();assert.equal(await page.locator('#memo-font').inputValue(),'serif');
 await page.locator('#memo-draw').click();const r=await page.locator('#memo-canvas').boundingBox();await page.mouse.move(r.x+60,r.y+60);await page.mouse.down();await page.mouse.move(r.x+250,r.y+180,{steps:10});await page.mouse.move(r.x+350,r.y+90,{steps:8});await page.mouse.up();await page.locator('#memo-draw-insert').click();await page.locator('#memo-drawing').waitFor({state:'hidden'});assert.equal(await page.locator('#memo-attachments img').count(),1);
 await page.locator('#memo-mic').click();await page.waitForFunction(()=>document.getElementById('memo-mic').getAttribute('aria-label')==='녹음 종료');await page.waitForTimeout(1400);await page.locator('#memo-mic').click();await page.waitForFunction(()=>document.querySelector('#memo-attachments audio'));await page.waitForFunction(()=>document.getElementById('memo-mic').getAttribute('aria-label')==='음성 녹음');
 await page.locator('#memo-more').click();await page.locator('#memo-color').selectOption('yellow');await page.locator('#memo-pin').click();await page.locator('#memo-more').click();await page.locator('#memo-star').click();await page.locator('#memo-close').click();await page.locator('#memo-editor').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelectorAll('.memo-card').length===1);
 // New memo saves while remaining open, then undo/redo retains its server identity.
 await page.locator('#open-memo-btn').click();await page.locator('#memo-title').fill('새 자동 저장');await page.waitForFunction(()=>document.getElementById('memo-status').textContent==='자동 저장됨');assert.equal(await page.locator('#memo-editor').isVisible(),true);
 await page.locator('#memo-body').evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));await page.locator('#memo-body').fill('한글 조합');await page.waitForTimeout(800);assert.equal(await page.locator('#memo-status').textContent(),'저장 대기…');await page.locator('#memo-body').evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await page.waitForFunction(()=>document.getElementById('memo-status').textContent==='자동 저장됨');
 await page.locator('#memo-undo').click();await page.locator('#memo-redo').click();await page.locator('#memo-close').click();await page.locator('#memo-editor').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelectorAll('.memo-card').length===2);
 await page.locator('.memo-card').filter({hasText:'새 자동 저장'}).click();await page.locator('#memo-more').click();await page.locator('[data-memo-action=delete]').click();await page.locator('#memo-action-confirm').click();await page.locator('#memo-editor').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelectorAll('.memo-card').length===1);
 // Editing during a delayed request must survive and must not create two memos.
 await page.locator('.memo-card').click();
 let held=false;await page.route('**/api/memos/*',async route=>{if(route.request().method()==='PUT'&&!held){held=true;await new Promise(r=>setTimeout(r,900));}await route.continue();});
 await page.locator('#memo-body').fill('첫 자동 저장');await page.waitForFunction(()=>document.getElementById('memo-status').textContent==='저장 중…');
 await page.locator('#memo-body').fill('저장 중에도 편집한 최종 내용');await page.waitForFunction(()=>document.getElementById('memo-status').textContent==='자동 저장됨');
 await page.locator('#memo-close').click();await page.locator('#memo-editor').waitFor({state:'hidden'});await page.locator('.memo-card').click();assert.equal(await page.locator('#memo-body').innerText(),'저장 중에도 편집한 최종 내용');await page.unroute('**/api/memos/*');
 // A failed save keeps the editor and text; explicit retry then closes safely.
 await page.route('**/api/memos/*',route=>route.request().method()==='PUT'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({message:'검증용 저장 실패'})}):route.continue());
 await page.locator('#memo-body').fill('실패 후 유지할 내용');await page.locator('#memo-retry').waitFor({state:'visible'});assert.equal(await page.locator('#memo-body').innerText(),'실패 후 유지할 내용');await page.locator('#memo-close').click();assert.equal(await page.locator('#memo-editor').isVisible(),true);await page.unroute('**/api/memos/*');await page.locator('#memo-retry').click();await page.waitForFunction(()=>document.getElementById('memo-status').textContent==='자동 저장됨');await page.locator('#memo-close').click();await page.locator('#memo-editor').waitFor({state:'hidden'});
 fs.mkdirSync((process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'',{recursive:true});await page.screenshot({path:(process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'/memo-list-pc.png'});await page.locator('.memo-card').click();await page.locator('#memo-editor').waitFor({state:'visible'});assert.equal(await page.locator('#memo-title').inputValue(),'회의 메모');assert.equal(await page.locator('#memo-attachments img').count(),1);assert.equal(await page.locator('#memo-attachments audio').count(),1);await page.screenshot({path:(process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'/memo-editor-pc.png'});await page.locator('#memo-more').click();await page.screenshot({path:(process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'/memo-menu-pc.png'});await page.locator('[data-memo-action=folder]').click();await page.locator('#memo-action-input').fill('업무');await page.locator('#memo-action-confirm').click();await page.locator('#memo-close').click();await page.locator('#memo-editor').waitFor({state:'hidden'});await page.reload();await page.locator('.memo-card').waitFor();await page.locator('.memo-card').click();await page.locator('#memo-editor').waitFor({state:'visible'});assert.equal(await page.locator('#memo-folder-label').textContent(),'업무');await page.setViewportSize({width:390,height:844});await page.screenshot({path:(process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'/memo-editor-mobile.png'});
 assert.equal(await page.locator('#memo-save').count(),0);
 assert.equal(await page.locator('.memo-editor-header #memo-undo').count(),1);
 await page.evaluate(()=>{Object.defineProperty(window.visualViewport,'height',{configurable:true,get:()=>440});window.visualViewport.dispatchEvent(new Event('resize'));});
 assert.equal(await page.locator('.memo-toolbar').isVisible(),false);
 await page.locator('#memo-title').focus();assert.equal(await page.locator('.memo-toolbar').isVisible(),true);await page.locator('#memo-keyboard').click();assert.equal(await page.locator('.memo-toolbar').isVisible(),false);
 await page.locator('#memo-body').focus();const toolbar=await page.locator('.memo-toolbar').boundingBox();assert.ok(toolbar.y+toolbar.height<=441);
 await page.locator('#memo-format-toggle').click();const format=await page.locator('#memo-format').boundingBox();assert.ok(format.y+format.height<=toolbar.y+1);
 await page.locator('#memo-more').click();await page.waitForFunction(()=>document.getElementById('memo-editor').dataset.editing==='false');assert.equal(await page.locator('.memo-toolbar').isVisible(),false);for(const button of await page.locator('#memo-menu button').all()){const box=await button.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390);assert.equal(await button.locator('svg').count(),1);}
 await page.screenshot({path:(process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'/memo-keyboard-menu-mobile.png'});await page.locator('#memo-more').click();
 await page.evaluate(()=>{delete window.visualViewport.height;window.visualViewport.dispatchEvent(new Event('resize'));});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#memo-close').click();if(await page.locator('#memo-action-dialog').isVisible())await page.locator('#memo-action-confirm').click();await page.locator('#memo-editor').waitFor({state:'hidden'});await page.screenshot({path:(process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'/memo-list-mobile.png'});await page.locator('#open-memo-search-btn').click();await page.locator('#memo-search').fill('없는메모');await page.locator('#memo-search-form [type=submit]').click();assert.equal(await page.locator('.memo-card').count(),0);await page.locator('#open-memo-search-btn').click();assert.equal(await page.locator('#memo-search').inputValue(),'없는메모');await page.locator('#memo-search-reset').click();assert.equal(await page.locator('.memo-card').count(),1);await page.locator('#open-memo-search-btn').click();await page.locator('#memo-search').fill('회의');await page.locator('#memo-search-close').click();assert.equal(await page.locator('.memo-card').count(),1);await page.locator('#open-memo-search-btn').click();assert.equal(await page.locator('#memo-search').inputValue(),'');await page.keyboard.press('Escape');assert.equal(await page.locator('#memo-search-dialog').isVisible(),false);await page.setViewportSize({width:1440,height:1000});await page.locator('#open-memo-search-btn').click();await page.screenshot({path:(process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'/memo-search-pc.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:(process.env.UI_CAPTURE_DIR||path.join(tmp,'captures'))+'/memo-search-mobile.png'});await page.goto('http://127.0.0.1:'+port+'/design-harness.html');await page.locator('#harness-view').selectOption('memos');await page.locator('#harness-search').click();await page.locator('#harness-search-input').fill('회의');await page.locator('#harness-search-form [type=submit]').click();assert.equal(await page.locator('#harness-state').textContent(),'검색 조건: 회의');await page.locator('#harness-search').click();await page.locator('#harness-search-reset').click();assert.equal(await page.locator('#harness-state').textContent(),'전체 목록');await page.locator('#harness-audit').click();assert.equal((await page.locator('#harness-result').textContent()).includes('FAIL'),false);assert.deepEqual(errors,[]);console.log('Memo browser PASS: autosave/reopen, delayed save editing, failure/retry, keyboard viewport toolbar/menu, font undo/redo, drawing, microphone recording, pinned/starred, folder, PC/mobile, no JS errors');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server?.close();fs.rmSync(tmp,{recursive:true,force:true});});

