/* Optional developer-only browser harness. Production UI has no browser dependencies. */
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
let chromium;
try{({chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright'));}catch{console.error('Optional browser QA needs Playwright. Install it in a development environment or set PLAYWRIGHT_MODULE_PATH.');process.exit(1);}
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'dailynote-ui-'));
delete process.env.REDIS_URL;delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.VERCEL;
process.env.DATA_DIR=path.join(tmp,'data');process.env.UPLOAD_DIR=path.join(tmp,'uploads');
const ds=require('../src/datastore'),{makeUserRecord}=require('../src/auth'),handler=require('../src/server');
const out=process.env.UI_CAPTURE_DIR||path.join(tmp,'captures');fs.mkdirSync(out,{recursive:true});
const password=crypto.randomBytes(24).toString('hex'),username='디자인검토';
let browser,server;
async function seed(){
 await ds.insert('users',{...makeUserRecord(username,password),role:'admin',active:true,approval:'approved'});
 await ds.insert('users',{...makeUserRecord('일반사용자',password),role:'member',active:true,approval:'approved'});
 await ds.insert('users',{...makeUserRecord('신규사용자',password),role:'member',active:false,approval:'pending'});
 await ds.insert('work_logs',{userId:1,workDate:'2026-10-01',todo:[{task:'사용자·관리자 메뉴 디자인 통일',checked:true},{task:'알림 상세페이지 검증',checked:false,children:[{task:'새로고침과 뒤로가기 확인',checked:false}]},{task:'온보딩 문서 정리',checked:false}],nextDayPlan:[{task:'팀원에게 시작 가이드 공유',checked:false}],remarks:'공통 UI 모듈을 사용하는 예시입니다.',memo:'중앙 제목 · 숨김 메뉴 · ＋ 팝업'});
 await ds.insert('notifications',{userId:1,message:'업무일지 화면이 새롭게 바뀌었습니다.\n\n왼쪽 메뉴와 중앙 제목을 확인하세요. 등록은 오른쪽 ＋에서 시작합니다.',isRead:false,createdAt:new Date().toISOString()});
 await ds.insert('site_settings',{values:{fontFamily:'system',fontSize:16,spacing:'normal',theme:'light',background:'none'}});
 fs.mkdirSync(process.env.UPLOAD_DIR,{recursive:true});fs.writeFileSync(path.join(process.env.UPLOAD_DIR,'sample.txt'),'예시 업무 자료');
 await ds.insert('files',{userId:1,originalName:'업무회의-자료.txt',storedName:'sample.txt',mimeType:'text/plain',sizeBytes:20,uploadedAt:new Date().toISOString()});
}
(async()=>{
 await seed();server=http.createServer(handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE_PATH?{executablePath:process.env.BROWSER_EXECUTABLE_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 async function settled(){await page.waitForFunction(()=>Array.from(document.querySelectorAll('.loading-overlay')).every(node=>node.hidden));}
 async function capture(name){await settled();await page.waitForTimeout(220);await page.screenshot({path:path.join(out,name+'.png')});}
 async function centered(){const r=await page.locator('.ui-title').boundingBox();assert.ok(Math.abs(r.x+r.width/2-page.viewportSize().width/2)<2,'Centered title');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'No horizontal overflow');}
 async function adminPanel(key){await page.locator('#admin-menu-toggle').click();await page.locator('[data-panel="'+key+'"]').click();await centered();}
 await page.goto(base);await page.locator('#username').fill(username);await page.locator('#password').fill(password);await page.locator('.login-btn').click();await page.locator('#main-section').waitFor({state:'visible'});await settled();await centered();await capture('01-user-worklogs');
 await page.locator('#sidebar-open').click();await capture('02-user-menu');await page.locator('[data-view="notifications"]').click();await capture('03-user-notifications');await page.locator('.notification-content').first().click();await page.waitForFunction(()=>document.getElementById('notification-page-message').textContent.length>0);await capture('04-user-notification-detail');await page.reload();await page.waitForFunction(()=>document.getElementById('notification-page-message').textContent.length>0);await settled();await page.locator('#notification-back').click();await page.waitForURL('**/#notifications');
 await page.locator('#sidebar-open').click();await page.locator('[data-view="files"]').click();await capture('05-user-files');await page.locator('#open-upload-btn').click();await capture('06-user-file-create');await page.locator('#upload-close').click();
 await page.goto(base+'/admin.html');await page.waitForFunction(()=>document.getElementById('admin-title').textContent==='알림 관리');await centered();await capture('07-admin-notifications');await page.locator('#admin-create').click();await capture('08-admin-notification-create');await page.locator('#notification-message').fill('   ');await page.locator('#notification-form button[type=submit]').click();await page.locator('#notification-form-error').filter({hasText:'알림 내용'}).waitFor();assert.equal(await page.locator('#notification-dialog').evaluate(node=>node.open),true);assert.equal(await page.locator('#notification-message').inputValue(),'   ');
 await page.locator('#notification-message').fill('브라우저 하네스 등록');await page.locator('#notification-form button[type=submit]').click();await page.waitForFunction(()=>!document.getElementById('notification-dialog').open);await settled();
 const created=page.locator('#admin-notifications .admin-row').filter({hasText:'브라우저 하네스 등록'});await created.getByRole('button',{name:'수정',exact:true}).click();assert.equal(await page.locator('#notification-message').inputValue(),'브라우저 하네스 등록');await capture('09-admin-notification-edit');await page.locator('#notification-message').fill('브라우저 하네스 수정');await page.locator('#notification-form button[type=submit]').click();await page.waitForFunction(()=>!document.getElementById('notification-dialog').open);await settled();await page.locator('#admin-notifications .admin-row').filter({hasText:'브라우저 하네스 수정'}).waitFor();
 await page.locator('#admin-menu-toggle').click();await capture('10-admin-menu');await page.locator('[data-panel="files"]').click();await capture('11-admin-files');await page.locator('#admin-create').click();await capture('12-admin-file-create');await page.locator('#admin-file').setInputFiles({name:'harness.txt',mimeType:'text/plain',buffer:Buffer.from('UI harness file')});await page.locator('#admin-upload-form button[type=submit]').click();await page.waitForFunction(()=>!document.getElementById('admin-upload-dialog').open);await settled();await page.locator('#admin-files .admin-row').filter({hasText:'harness.txt'}).waitFor();
 for(const [key,name] of [['users','13-admin-users'],['appearance','14-admin-appearance'],['permissions','15-admin-permissions']]){await adminPanel(key);await capture(name);}
 await page.goto(base+'/onboarding.html');await centered();await capture('16-onboarding');await page.goto(base+'/design-harness.html');await centered();await page.locator('#harness-audit').click();assert.ok(!(await page.locator('#harness-result').textContent()).includes('FAIL'));await capture('17-design-harness');await page.locator('#harness-create').click();await page.locator('#harness-form button[type=submit]').click();await page.locator('#harness-error').filter({hasText:'내용을 입력하세요.'}).waitFor();await page.locator('#harness-input').fill('예시 검증');await page.locator('#harness-form button[type=submit]').click();assert.equal(await page.locator('#harness-dialog').evaluate(node=>node.open),false);
 await page.setViewportSize({width:390,height:844});await page.locator('#harness-audit').click();assert.ok(!(await page.locator('#harness-result').textContent()).includes('FAIL'));await page.goto(base+'/#notifications/1');await page.waitForFunction(()=>document.getElementById('notification-page-message').textContent.length>0);await settled();await centered();await capture('18-mobile-notification-detail');await page.locator('#notification-back').click();await page.locator('#sidebar-open').click();await page.locator('[data-view="worklogs"]').click();await capture('19-mobile-worklogs');await page.goto(base+'/admin.html');await settled();await centered();await page.locator('#admin-create').click();await capture('20-mobile-admin-notification-popup');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'passed',viewports:['1440x1000','390x844'],captures:20,output:out,checks:['centered titles','no overflow','notification detail reload/back','notification create/update','error preserves input','file upload','harness error/save','no page errors']}));
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));if(out.startsWith(tmp))console.log('Temporary captures: '+out);else fs.rmSync(tmp,{recursive:true,force:true});});
