const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'boards-browser-'));process.env.DATA_DIR=path.join(tmp,'data');process.env.UPLOAD_DIR=path.join(tmp,'uploads');delete process.env.REDIS_URL;delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.VERCEL;
const ds=require('../src/datastore'),{makeUserRecord}=require('../src/auth'),handler=require('../src/server');let server,browser;
(async()=>{
 await ds.insert('users',{...makeUserRecord('검토계정','local-password-123'),role:'admin',approval:'approved'});await ds.insert('site_settings',{values:{background:'none'}});await ds.insert('memos',{userId:1,title:'참조 메모',text:'선택한 내용',attachments:[]});
 server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('#username').fill('검토계정');await page.locator('#password').fill('local-password-123');await page.locator('.login-btn').click();await page.locator('#main-section').waitFor({state:'visible'});await page.waitForFunction(()=>document.getElementById('loading-overlay').hidden);
 await page.goto(base+'/admin.html#boards');await page.locator('#panel-boards').waitFor({state:'visible'});await page.locator('#admin-create').click();await page.locator('#board-manage-name').fill('개발 공유');await page.locator('#board-manage-categories').fill('개발\n자료');await page.locator('#board-manage-description').fill('코드와 자료를 공유하는 게시판입니다.');await page.locator('#board-manage-save').click();await page.locator('.board-admin-row strong').waitFor();assert.equal(await page.locator('.board-admin-row strong').textContent(),'개발 공유');
 await page.goto(base+'/#boards/1');await page.locator('#board-create').waitFor({state:'visible'});await page.locator('#board-create').click();await page.locator('#board-title').fill('코드와 이미지 공유');await page.locator('#board-category').selectOption('개발');await page.locator('#board-body').fill('본문 테스트');await page.locator('#board-code-add').click();await page.locator('#board-code-text').fill('const value = "공유";\n// 예시 코드\nconsole.log(value);');await page.locator('#board-code-form button[type=submit]').click();
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZAAAAABJRU5ErkJggg==','base64');await page.locator('#board-image-input').setInputFiles({name:'테스트.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>document.getElementById('board-attachments').textContent.includes('테스트.png')&&!document.getElementById('board-save').disabled);
 await page.locator('#board-draw-add').click();const canvas=await page.locator('#board-canvas').boundingBox();await page.mouse.move(canvas.x+30,canvas.y+30);await page.mouse.down();await page.mouse.move(canvas.x+90,canvas.y+60);await page.mouse.up();await page.locator('#board-draw-insert').click();await page.locator('#board-drawing').waitFor({state:'hidden'});await page.locator('#board-tags').fill('#코드 #공유');await page.locator('#board-reference-add').click();await page.locator('#board-picker-list button').filter({hasText:'참조 메모'}).click();await page.locator('#board-mention-add').click();await page.locator('#board-picker-list button').filter({hasText:'검토계정'}).click();await page.route('**/api/boards/1/posts',route=>route.request().method()==='POST'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'저장 실패 검증'})}):route.continue());await page.locator('#board-save').click();await page.waitForFunction(()=>document.getElementById('board-form-error').textContent.includes('저장 실패'));assert.equal(await page.locator('#board-title').inputValue(),'코드와 이미지 공유');await page.unroute('**/api/boards/1/posts');await page.locator('#board-save').click();await page.waitForURL(/posts\/1$/);await page.locator('.board-code-view').waitFor();await page.locator('.board-inline-image img').first().waitFor();assert.ok(await page.locator('.code-keyword').count());assert.equal(await page.locator('.board-reference summary').textContent(),'참조 · 참조 메모');
 await page.locator('.board-inline-image').first().click();await page.locator('#board-image-view').waitFor({state:'visible'});await page.locator('[data-board-close=board-image-view]').click();
 await page.locator('#board-more').click();await page.locator('#board-menu-items button').filter({hasText:'복제',exact:true}).click();assert.equal(await page.locator('#board-title').inputValue(),'코드와 이미지 공유 (복제)');await page.locator('#board-save').click();await page.waitForURL(/posts\/2$/);await page.reload();await page.locator('.board-detail h2').waitFor();assert.equal(await page.locator('.board-detail h2').textContent(),'코드와 이미지 공유 (복제)');
 await page.locator('#notification-back').click();await page.waitForURL(/boards\/1$/);await page.locator('.board-post-row').first().waitFor();await page.locator('#board-search').click();await page.locator('#board-query').fill('복제');await page.locator('#board-search-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelectorAll('.board-post-row').length===1);
 await page.locator('#board-more').click();const download=page.waitForEvent('download');await page.locator('#board-menu-items button').filter({hasText:'엑셀 다운로드'}).click();const d=await download;assert.ok(d.suggestedFilename().endsWith('.xlsx'));await page.keyboard.press('Escape');
