const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const JSZip=require('../public/vendor/jszip/jszip.min');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'dailynote-backup-browser-'));delete process.env.REDIS_URL;delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.VERCEL;
process.env.DATA_DIR=path.join(tmp,'data');process.env.UPLOAD_DIR=path.join(tmp,'uploads');
const ds=require('../src/datastore'),storage=require('../src/file-storage'),{makeUserRecord}=require('../src/auth'),handler=require('../src/server');
const captures=process.env.UI_CAPTURE_DIR||path.join(tmp,'captures');fs.mkdirSync(captures,{recursive:true});let browser,server,page;
(async()=>{
 const password=crypto.randomBytes(24).toString('hex');await ds.insert('users',{...makeUserRecord('백업관리자',password),role:'admin',active:true});await ds.insert('users',{...makeUserRecord('백업사용자',password),role:'member',active:true});
 await ds.insert('work_logs',{userId:1,workDate:'2026-10-01',todo:[{task:'백업 상위',checked:true,children:[{task:'하위\n줄바꿈',checked:false}]}],nextDayPlan:['익일 계획'],memo:'메모',remarks:'비고'});
 await ds.insert('memos',{userId:1,title:'첨부 메모',text:'사진과 음성',html:'사진과 음성',folder:'',font:'sans-serif',color:'white',attachments:[{kind:'audio',name:'녹음',data:'data:audio/wav;base64,YWJj'}]});
 for(let i=0;i<3;i++){const name='example-'+i;await storage.write(name,Buffer.from('bytes-'+i));await ds.insert('files',{userId:1,originalName:i<2?'같은이름.txt':'세번째.txt',storedName:name,mimeType:'text/plain',sizeBytes:7,uploadedAt:new Date().toISOString()});}
 server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH,args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--disable-crash-reporter']});page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
 async function settled(){await page.waitForFunction(()=>Array.from(document.querySelectorAll('.loading-overlay')).every(n=>n.hidden));}
 async function login(username){await page.goto(base);await page.locator('#username').fill(username);await page.locator('#password').fill(password);await page.locator('.login-btn').click();await page.locator('#main-section').waitFor({state:'visible'});await settled();}
 async function route(key){await page.goto(base+'/#'+key);await page.locator('#main-section').waitFor({state:'visible'});await settled();}
 async function menu(label,admin=false){if(admin){await page.getByRole('button',{name:label.replace('전체 불러오기','전체 복원'),exact:true}).click();}else{await page.locator('#menu-tools').click();await page.locator('#data-menu').getByRole('menuitem',{name:label,exact:true}).click();}}
 async function download(action){const event=page.waitForEvent('download',{timeout:10000}).catch(async e=>{console.error('PAGE STATUS',await page.locator('.data-status').textContent(),'ERRORS',errors);throw e;});await action();const result=await event;const file=path.join(tmp,crypto.randomUUID()+'.zip');await result.saveAs(file);await page.locator('#data-dialog .data-status').filter({hasText:'다운로드를 시작했습니다'}).waitFor();await page.locator('#data-close').click();return {zip:await JSZip.loadAsync(fs.readFileSync(file),{checkCRC32:true}),file};}
 async function load(label,files,admin=false){await menu(label,admin);await page.locator('input[type=file][accept=".zip,.json"]').setInputFiles(files);await page.locator('#data-restore').waitFor({state:'visible'});}
 await login('백업관리자');const archive=await download(()=>menu('일정 백업'));const manifest=JSON.parse(await archive.zip.file('manifest.json').async('string'));assert.equal(manifest.records.work_logs.length,1);assert.equal(manifest.records.work_logs[0].todo[0].children[0].task,'하위\n줄바꿈');
 await load('일정 불러오기',archive.file);await page.screenshot({path:path.join(captures,'backup-preview-pc.png')});await page.locator('#data-restore').click();await page.locator('#data-dialog .data-status').filter({hasText:'불러오기를 완료했습니다'}).waitFor();await page.locator('#data-close').click();assert.equal((await ds.findAll('work_logs')).length,2);
 await load('일정 불러오기',archive.file);await page.locator('#data-restore').click();await page.locator('#data-dialog .data-status').filter({hasText:'이미 불러온 백업'}).waitFor();await page.locator('#data-close').click();assert.equal((await ds.findAll('work_logs')).length,2);
 await load('일정 불러오기',{name:'work_logs.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{id:10,userId:1,workDate:'2026-09-30',todo:['초기 데이터 항목'],nextDayPlan:['초기 계획'],remarks:'이전 비고',memo:'이전 메모'}]))});await page.locator('#data-dialog .data-status').filter({hasText:'이전 JSON 형식'}).waitFor();await page.locator('#data-restore').click();await page.locator('#data-dialog .data-status').filter({hasText:'불러오기를 완료했습니다'}).waitFor();await page.locator('#data-close').click();assert.equal((await ds.findAll('work_logs')).at(-1).todo[0].task,'초기 데이터 항목');
 await route('files');await menu('파일 선택 다운로드');await page.locator('.file-pick input').nth(1).check();assert.equal(await page.locator('.file-selection span').textContent(),'1개 선택');const picked=await download(()=>page.locator('.file-selection').getByRole('button',{name:'선택 다운로드',exact:true}).click());assert.equal(Object.values(picked.zip.files).filter(e=>!e.dir).length,1);assert.equal(await picked.zip.file('같은이름.txt').async('string'),'bytes-1');
 await page.setViewportSize({width:390,height:844});await page.locator('#menu-tools').click();await page.screenshot({path:path.join(captures,'file-menu-mobile.png')});await page.keyboard.press('Escape');const all=await download(()=>menu('파일 전체 다운로드 (ZIP)'));assert.equal(Object.values(all.zip.files).filter(e=>!e.dir).length,3);assert.equal(await all.zip.file('같은이름.txt').async('string'),'bytes-0');assert.equal(await all.zip.file('2_같은이름.txt').async('string'),'bytes-1');
 const missing=new JSZip();missing.file('data/files.json',JSON.stringify([{id:99,originalName:'누락.txt',storedName:'missing',sizeBytes:3}]));const missingBytes=await missing.generateAsync({type:'nodebuffer'});await menu('파일 불러오기');await page.locator('input[type=file][accept=".zip,.json"]').setInputFiles({name:'old-missing.zip',mimeType:'application/zip',buffer:missingBytes});await page.locator('#data-dialog .data-status').filter({hasText:'원본이 없습니다'}).waitFor();assert.equal(await page.locator('#data-restore').isVisible(),false);await page.locator('#data-close').click();assert.equal((await ds.findAll('files')).length,3);
 const legacy=new JSZip();legacy.file('data/files.json',JSON.stringify([{id:99,userId:88,originalName:'초기파일.txt',storedName:'original.txt',sizeBytes:3,mimeType:'text/plain'}]));legacy.file('uploads/original.txt','old');await load('파일 불러오기',{name:'initial-data.zip',mimeType:'application/zip',buffer:await legacy.generateAsync({type:'nodebuffer'})});await page.screenshot({path:path.join(captures,'legacy-preview-mobile.png')});await page.locator('#data-restore').click();await page.locator('#data-dialog .data-status').filter({hasText:'불러오기를 완료했습니다'}).waitFor();await page.locator('#data-close').click();assert.equal((await ds.findAll('files')).at(-1).userId,1);assert.equal((await ds.findAll('files')).length,4);
 await route('memos');const memoArchive=await download(()=>menu('메모 백업'));assert.equal(JSON.parse(await memoArchive.zip.file('manifest.json').async('string')).records.memos[0].attachments.length,1);
 await page.goto(base+'/admin.html');await settled();await page.locator('#admin-menu-toggle').click();await page.locator('[data-panel=backups]').click();await settled();const full=await download(()=>menu('전체 백업',true));const fullManifest=JSON.parse(await full.zip.file('manifest.json').async('string'));assert.equal(fullManifest.records.files.length,4);assert.equal(fullManifest.records.users.length,2);assert.equal(fullManifest.records.sessions,undefined);assert.ok(full.zip.file('files/4.bin'));
 await load('전체 불러오기',full.file,true);await page.screenshot({path:path.join(captures,'all-backup-preview-mobile.png')});assert.equal(await page.locator('#apply-management').isChecked(),true);await page.locator('#data-restore').click();await page.locator('#data-dialog .data-status').filter({hasText:'불러오기를 완료했습니다'}).waitFor();await page.locator('#data-close').click();assert.equal((await ds.findAll('files')).length,8);assert.equal((await ds.findAll('users')).length,2);
 await page.locator('#admin-menu-toggle').click();await page.locator('[data-panel=logs]').click();await settled();await page.locator('#logs-list .admin-row').first().waitFor();await page.locator('#admin-search').click();await page.locator('#log-category').selectOption('backup');await page.locator('#log-search-form button[type=submit]').click();await settled();await page.screenshot({path:path.join(captures,'logs-mobile.png')});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 console.log(JSON.stringify({status:'passed',checks:['XLSX covered by common UI harness','menu backup ZIP','preview and duplicate restore','initial JSON restore','missing original rejected','legacy uploads ZIP restore','selected/whole file ZIP and duplicate filenames','memo attachments','administrator whole backup/restore','no external requests or page errors'],captures}));
})().catch(async e=>{console.error('UI ERROR STATUS',await page?.locator('.data-status').textContent().catch(()=>''));console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));});
