const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'boards-browser-'));process.env.DATA_DIR=path.join(tmp,'data');process.env.UPLOAD_DIR=path.join(tmp,'uploads');delete process.env.REDIS_URL;delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.VERCEL;
const ds=require('../src/datastore'),{makeUserRecord}=require('../src/auth'),handler=require('../src/server');let server,browser;
(async()=>{
 await ds.insert('users',{...makeUserRecord('검토계정','local-password-123'),role:'admin',approval:'approved'});await ds.insert('site_settings',{values:{background:'none'}});await ds.insert('memos',{userId:1,title:'참조 메모',text:'선택한 내용',attachments:[]});
 server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('#username').fill('검토계정');await page.locator('#password').fill('local-password-123');await page.locator('.login-btn').click();await page.locator('#main-section').waitFor({state:'visible'});await page.waitForFunction(()=>document.getElementById('loading-overlay').hidden);
 await page.goto(base+'/admin.html#boards');await page.locator('#panel-boards').waitFor({state:'visible'});await page.locator('#admin-create').click();await page.locator('#board-manage-name').fill('개발 공유');await page.locator('#board-manage-categories').fill('개발\n자료');await page.locator('#board-manage-description').fill('코드와 자료를 공유하는 게시판입니다.');await page.locator('#board-manage-save').click();await page.locator('.board-admin-row strong').waitFor();assert.equal(await page.locator('.board-admin-row strong').textContent(),'개발 공유');
 await page.goto(base+'/#boards/1');await page.locator('#board-create').waitFor({state:'visible'});await page.locator('#board-create').click();await page.locator('#board-title').fill('코드와 이미지 공유');await page.locator('#board-category').selectOption('개발');await page.locator('#board-body').fill('본문 테스트');await page.locator('#board-undo').click();assert.equal(await page.locator('#board-body').innerText(),'');await page.locator('#board-redo').click();assert.equal(await page.locator('#board-body').innerText(),'본문 테스트');await page.locator('#board-format-toggle').click();await page.locator('[data-board-value=h2]').click();assert.equal(await page.locator('#board-body h2').innerText(),'본문 테스트');await page.locator('#board-undo').click();assert.equal(await page.locator('#board-body h2').count(),0);await page.locator('#board-format-toggle').click();await page.locator('#board-code-add').click();await page.locator('#board-code-text').fill('const value = "공유";\n// 예시 코드\nconsole.log(value);');await page.locator('#board-code-form button[type=submit]').click();
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZAAAAABJRU5ErkJggg==','base64');await page.locator('#board-image-input').setInputFiles({name:'테스트.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>document.getElementById('board-attachments').textContent.includes('테스트.png')&&!document.getElementById('board-save').disabled);
 await page.locator('#board-draw-add').click();const canvas=await page.locator('#board-canvas').boundingBox();await page.mouse.move(canvas.x+30,canvas.y+30);await page.mouse.down();await page.mouse.move(canvas.x+90,canvas.y+60);await page.mouse.up();await page.locator('#board-draw-insert').click();await page.locator('#board-drawing').waitFor({state:'hidden'});await page.locator('#board-tags').fill('#코드 #공유');await page.locator('#board-reference-add').click();await page.locator('#board-picker-list button').filter({hasText:'참조 메모'}).click();await page.locator('#board-mention-add').click();await page.locator('#board-picker-list button').filter({hasText:'검토계정'}).click();await page.route('**/api/boards/1/posts',route=>route.request().method()==='POST'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'저장 실패 검증'})}):route.continue());await page.locator('#board-save').click();await page.waitForFunction(()=>document.getElementById('board-form-error').textContent.includes('저장 실패'));assert.equal(await page.locator('#board-title').inputValue(),'코드와 이미지 공유');await page.unroute('**/api/boards/1/posts');await page.locator('#board-save').click();await page.waitForURL(/posts\/1$/);await page.locator('.board-code-view').waitFor();await page.locator('.board-inline-image img').first().waitFor();assert.ok(await page.locator('.code-keyword').count());assert.equal(await page.locator('.board-reference summary').textContent(),'참조 · 참조 메모');
 await page.locator('.board-inline-image').first().click();await page.locator('#board-image-view').waitFor({state:'visible'});await page.locator('[data-board-close=board-image-view]').click();
 await page.locator('#board-more').click();await page.locator('#board-menu-items button').filter({hasText:'복제',exact:true}).click();assert.equal(await page.locator('#board-title').inputValue(),'코드와 이미지 공유 (복제)');await page.locator('#board-save').click();await page.waitForURL(/posts\/2$/);await page.reload();await page.locator('.board-detail h2').waitFor();assert.equal(await page.locator('.board-detail h2').textContent(),'코드와 이미지 공유 (복제)');
 await page.locator('#notification-back').click();await page.waitForURL(/boards\/1$/);await page.locator('.board-post-row').first().waitFor();await page.locator('#board-search').click();await page.locator('#board-query').fill('복제');await page.locator('#board-search-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelectorAll('.board-post-row').length===1);
 await page.locator('#board-more').click();const download=page.waitForEvent('download');await page.locator('#board-menu-items button').filter({hasText:'엑셀 다운로드'}).click();const d=await download;assert.ok(d.suggestedFilename().endsWith('.xlsx'));await page.keyboard.press('Escape');
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
 await page.setViewportSize(viewport);await page.locator('#board-more').click();
 const menu=await page.locator('#board-menu').boundingBox();assert.ok(menu.x>=12&&menu.x+menu.width<=viewport.width-11&&menu.y>=12&&menu.y+menu.height<=viewport.height-11);
 assert.equal(await page.locator('#board-menu-items button').count(),await page.locator('#board-menu-items button > svg').count());assert.equal(await page.locator('#board-more').getAttribute('aria-expanded'),'true');
 await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'게시판 링크 공유');await page.keyboard.press('End');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'게시판 관리');
 await page.keyboard.press('Escape');await page.waitForFunction(()=>document.getElementById('board-more').getAttribute('aria-expanded')==='false');await page.locator('#board-more').click();await page.mouse.click(4,viewport.height-4);await page.locator('#board-menu').waitFor({state:'hidden'});
 }
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){await page.setViewportSize(viewport);await page.locator('#board-create').click();assert.ok(await page.locator('#board-body').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const rect=await page.locator('#board-editor').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=viewport.width+1);const bar=await page.locator('.editor-header').boundingBox();assert.ok(bar.y>=0&&bar.y+bar.height<=viewport.height);const tools=await page.locator('.editor-tools').boundingBox();assert.ok(tools.y+tools.height<=viewport.height+1);const topUndo=await page.locator('#board-undo').boundingBox();assert.ok(topUndo.y<100);const heading=await page.locator('#board-editor-heading').boundingBox();assert.ok(Math.abs(heading.x+heading.width/2-viewport.width/2)<2);await page.locator('#board-title').fill('취소 전');await page.locator('#board-title').fill('취소 후');await page.locator('#board-title').press('Control+z');assert.equal(await page.locator('#board-title').inputValue(),'취소 전');await page.locator('#board-title').press('Control+Shift+z');assert.equal(await page.locator('#board-title').inputValue(),'취소 후');if(process.env.UI_CAPTURE_DIR){fs.mkdirSync(process.env.UI_CAPTURE_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.UI_CAPTURE_DIR,'board-editor-'+viewport.width+'.png')});}await page.locator('[data-board-close=board-editor]').first().click();const title=await page.locator('#shell-title').boundingBox();assert.ok(Math.abs(title.x+title.width/2-viewport.width/2)<2);}
 const seed=(await ds.findAll('board_posts'))[0];for(let n=0;n<48;n++)await ds.insert('board_posts',{...seed,id:undefined,title:'페이징 '+n,attachments:[],references:[],mentions:[]});
 await page.locator('#board-search').click();await page.locator('#board-search-reset').click();await page.waitForFunction(()=>document.querySelectorAll('.board-post-row').length===20);await page.evaluate(()=>{const e=document.getElementById('main-section');e.scrollTop=e.scrollHeight;});await page.waitForFunction(()=>document.querySelectorAll('.board-post-row').length>=40);assert.ok(await page.locator('.board-post-row').count()<=50);
 const hostile=await ds.insert('board_posts',{...seed,id:undefined,title:'서식 검증',html:'<script>window.boardXSS=true</script><img src=x onerror="window.boardXSS=true"><svg onload="window.boardXSS=true"></svg><p onclick="window.boardXSS=true">안전한 본문</p>'});await page.goto(base+'/#boards/1/posts/'+hostile.id);await page.locator('.board-detail h2').waitFor();assert.equal(await page.evaluate(()=>window.boardXSS),undefined);assert.equal(await page.locator('.board-rich [onclick],.board-rich svg,.board-rich script').count(),0);
 // Unknown and deleted direct URLs retain the board route and render an error.
 await page.goto(base+'/#boards/1/posts/99999');await page.waitForFunction(()=>document.getElementById('board-status').textContent.includes('삭제'));assert.equal(await page.locator('#board-create').isVisible(),false);

 // Management rows stack details below the title and expose actions only via ….
 const emptyBoard=await ds.insert('boards',{name:'빈 게시판 삭제 검증',group:'공유게시판',description:'메뉴에서 삭제 테스트',categories:[],active:true,inMenu:true,order:1});
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  await page.setViewportSize(viewport);await page.goto(base+'/admin.html#boards');await page.locator('.board-admin-row').first().waitFor();
  const row=page.locator('.board-admin-row').filter({hasText:'개발 공유'}),more=row.locator('.board-admin-more');
  assert.equal(await row.locator('button').count(),1);assert.equal(await row.locator('a').count(),0);
  const title=await row.locator('strong').boundingBox(),meta=await row.locator('.board-admin-meta').first().boundingBox();assert.ok(meta.y>=title.y+title.height);
  assert.equal(await row.locator('.board-admin-description').textContent(),'코드와 자료를 공유하는 게시판입니다.');
  await more.click();await page.locator('#board-admin-menu').waitFor({state:'visible'});
  assert.equal(await page.locator('.board-admin-menu-items button').count(),2);assert.equal(await page.locator('.board-admin-menu-items a').textContent(),'게시판 열기');
  const box=await page.locator('#board-admin-menu').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=viewport.width+1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  if(process.env.UI_CAPTURE_DIR){fs.mkdirSync(process.env.UI_CAPTURE_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.UI_CAPTURE_DIR,'board-admin-menu-'+viewport.width+'.png')});}
  await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement.classList.contains('board-admin-more'));
  await more.click();await page.locator('.board-admin-menu-items button').filter({hasText:'설정',exact:true}).click();await page.locator('#board-manage-dialog').waitFor({state:'visible'});assert.equal(await page.locator('#board-manage-name').inputValue(),'개발 공유');await page.locator('#board-manage-close').click();
  await more.click();await page.locator('.board-admin-menu-items button').filter({hasText:'삭제',exact:true}).click();await page.locator('#board-admin-delete-dialog').waitFor({state:'visible'});await page.locator('#board-admin-delete-confirm').click();await page.locator('#board-admin-delete-error').filter({hasText:'비활성화'}).waitFor();assert.ok(await ds.findOne('boards',b=>b.id===1));await page.keyboard.press('Escape');
  await more.click();await page.locator('.board-admin-menu-items a').click();await page.waitForURL(/boards\/1$/);await page.locator('.board-post-row').first().waitFor();
 }
 await page.goto(base+'/admin.html#boards');const emptyRow=page.locator('.board-admin-row').filter({hasText:'빈 게시판 삭제 검증'});await emptyRow.locator('.board-admin-more').click();await page.locator('.board-admin-menu-items button').filter({hasText:'삭제',exact:true}).click();await page.locator('#board-admin-delete-confirm').click();await emptyRow.waitFor({state:'detached'});assert.equal(await ds.findOne('boards',b=>b.id===emptyBoard.id),undefined);
 assert.deepEqual(errors,[]);console.log('PASS boards: admin create/menu, rich code, image, references, mentions, duplicate, direct URL/reload/back, search, XLSX, PC/mobile layout, missing post, management more/settings/open/delete, title/details layout, Escape/focus, nonempty deletion blocked');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.rmSync(tmp,{recursive:true,force:true});});
